stages:
  - build
  - sonarqube-check
  - sonarqube-vulnerability-report
  - test
  - push_to_staging
  - backup
  - deploy

build:
  stage: build
  script:
    - docker build --build-arg ENVIRONMENT=$CI_COMMIT_REF_NAME -t fredzengue/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME .
  only:
    - Dev
    - staging
    - main

backup:
  stage: backup
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - docker push fredzengue/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME
  only:
    - Dev
    - staging
    - main
test:
  stage: test
  script:
    echo test comming soon
    # - npm test

# push_to_staging:
#   image: alpine:latest
#   stage: push_to_staging
#   before_script:
#     - apk --no-cache add curl jq
#   script:
#     - curl --version
#     - jq --version
#     -  >
#       MR_INFO=$(curl --request POST --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --header "Content-Type: application/json"
#       --data "{\"source_branch\": \"$CI_COMMIT_REF_NAME\", \"target_branch\": \"staging\", \"title\": \"Auto merge Dev into staging\", \"merge_when_pipeline_succeeds\": true}"
#       "https://gitlab.dsp5-archi-o22a-15m-g3.site/api/v4/projects/$CI_PROJECT_ID/merge_requests")

#     - echo $MR_INFO
#     - MR_ID=$(echo "$MR_INFO" | jq -r .iid)
#     - echo $MR_ID
#     - >
#       MR_INFO=$(curl --request PUT --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" --header "Content-Type: application/json"
#       -d '{"should_remove_source_branch": "false", "merge_when_pipeline_succeeds": "true"}'
#       "https://gitlab.dsp5-archi-o22a-15m-g3.site/api/v4/projects/$CI_PROJECT_ID/merge_requests/$MR_ID")
#     - echo $MR_INFO
        

#   only:
#     - Dev

variables:
  DOCKER_TLS_CERTDIR: "/certs"

sonarqube-check:
  stage: sonarqube-check
  image:
    name: sonarsource/sonar-scanner-cli:5.0
    entrypoint: [""]
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar" # Defines the location of the analysis task cache
    GIT_DEPTH: "0" # Tells git to fetch all the branches of the project, required by the analysis task
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  allow_failure: true

sonarqube-vulnerability-report:
  image: curlimages/curl
  stage: sonarqube-vulnerability-report
  script:
    - 'curl -u "${SONAR_TOKEN}:" "${SONAR_HOST_URL}/api/issues/gitlab_sast_export?projectKey=root_the_tip_top_webapp_243d3330-f205-4073-936d-ee28d2ce8d8d&branch=${CI_COMMIT_BRANCH}&pullRequest=${CI_MERGE_REQUEST_IID}" -o gl-sast-sonar-report.json'
  allow_failure: true
  artifacts:
    expire_in: 1 day
    reports:
      sast: gl-sast-sonar-report.json
  dependencies:
    - sonarqube-check

deploy in staging:
  stage: deploy
  script:
    - docker exec ansible-master ansible-playbook deploy_staging_thetiptop.yml --extra-vars "DOCKER_REGISTRY=fredzengue/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
  only:
    - staging

deploy in prod:
  stage: deploy
  script:
    - docker exec ansible-master ansible-playbook deploy_thetiptop.yml --extra-vars "DOCKER_REGISTRY=fredzengue/$CI_PROJECT_NAME:$CI_COMMIT_REF_NAME"
  only:
    - main
